---
apiVersion: v1
kind: Namespace
metadata:
  name: staging
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: express
  namespace: staging
  labels:
    app: express
spec:
  replicas: 2
  selector:
    matchLabels:
      app: express
  template:
    metadata:
      labels:
        app: express
    spec:
      containers:
      - name: express
        image: xxxxx.dkr.ecr.us-east-2.amazonaws.com/ashutoshkubertest:v1.0.0
        ports:
        - name: http
          containerPort: 8080
        resources:
          requests:
            memory: 64Mi
            cpu: 100m
          limits:
            memory: 128Mi
            cpu: 300m
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: express
  namespace: staging
spec:
  selector:
    app: express
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer
